name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

pool: Selfhosted-Agent-Ubuntu-20.04

trigger: none

stages :
  - stage: Setup
    jobs:
    - job: TerraformCreateUserProject
      continueOnError: false
      steps:
        - task: Bash@3
          displayName: 'Show working directory'
          inputs:
            targetType: inline
            failOnStderr: true
            workingDirectory: $(System.DefaultWorkingDirectory)/iac
            script: |
              echo "### Testing ADO Agent, show default working directory:"
              echo $(System.DefaultWorkingDirectory)
        - task: Bash@3
          displayName: 'Perform terraform commands'
          inputs:
            targetType: inline
            failOnStderr: false
            workingDirectory: $(System.DefaultWorkingDirectory)/iac
            script: |
              source .env.tmp
              env
              terraform init
              #terraform show -json | jq '.values.root_module.resources[] | select(.address == "azuredevops_project.core_project") | .values
              ls -alr
              terraform destroy -auto-approve