name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

pool: Selfhosted-Agent-Ubuntu-20.04

trigger: none

stages :
  - stage: Test
    jobs:
    - job: ShowWorkingDirectoy
      continueOnError: false
      steps:
        - task: Bash@3
          displayName: 'Show working directory'
          inputs:
            targetType: inline
            script: |
              echo "Testing ADO Agent, show default working directory:"
              echo $(System.DefaultWorkingDirectory)
            failOnStderr: true
            workingDirectory: $(System.DefaultWorkingDirectory)